###
POST {{content_host}}/content/course/list?pageNo=2&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

###
GET {{content_host}}/content/course-category/tree-nodes

###
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 0,
  "originalPrice": 0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "",
  "st": "",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": ""
}
