###
POST {{content_host}}/content/course/list?pageNo=2&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

###
GET {{content_host}}/content/course-category/tree-nodes
