### 通过网关访问资源服务
GET http://localhost:63010/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MTM5MzU3MzgsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImE1Mjg1Nzk2LWQzZWYtNGYwYS1iN2Y5LWE4N2U0ZDVhNmQ1OCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.hn-vqBResKtfY9JDDHrOsVSiJ6MXOdQWnbcX2cb8nDY

